server:
  port: 6002
spring:
  application:
    name: study-first-webmagic
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/first?characterEncoding=utf-8
    username: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 127.0.0.1
jwt:
  config:
    key: itcast
    ttl: 360000