server:
  port: 6002
spring:
  application:
    name: baidu-image
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://47.103.11.24:3306/first?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    database: mysql
    show-sql: true

